# Generated by cucumber-sinatra. (2013-11-19 18:53:30 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/project.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Project

class ProjectWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ProjectWorld.new
end
